### ISSUE TITLE
jquery and waypoints not working

### ISSUE THREAD

**Issue by NaomiRison** [bigu21/meteor-waypoints#3]
project is here: https://github.com/NaomiRison/coffee-website

 getting error: GET file:///C:/Users/nrris/Desktop/fe101/coffeewebsite/waypoints.min.js net::ERR_FILE_NOT_FOUND
scripts.js:3 Uncaught TypeError: $(...).waypoint is not a function
    at scripts.js:3

for some reason jquery and jquery  waypoints is not working at all.

 They are properly ordered in my html file, so I dont get whats wrong....HELP.   When I click the button for mobile devices, navbar does not show up at all.  I dont have the scrolling effect that I want....HELP

**Comment by pedroeusebio** [comment]
Hi NaomiRison,

Your issue was addressed to the wrong repository. I saw your code and you are using jquery waypoints implementation. 
So,i think have found an error in your code. In the index.html, you didn't added jquery.waypoints.min.js, so that's why you can't access this function:
 `<script src="waypoints.min.js"></script> // file index.html, line 76`
Try to correct your code and add the right source:
` <script src="jquery.waypoints.min.js"></script>`
